var data = {
    "uzbek": {
        // petro
        "petrotitle": "O'zbek Petro",
        "petrotext1": "Salom men Petro va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        "petrotext2": "Salom men Petro va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        // little
        "littletitle": "O'zbek Mayda",
        "littletext1": "Salom men Mayda va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        "littletext2": "Salom men Mayda va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        // alisa
        // little
        "alisatitle": "O'zbek Alisa",
        "alisatext1": "Salom men Alisa va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        "alisatext2": "Salom men Alisa va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
    },
    "russian": {
        // petro
        "petrotitle": "Рус Петро",
        "petrotext1": "Привет, меня зовут Петро и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        "petrotext2": "Привет, меня зовут Петро и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        // little
        "littletitle": "Рус Маленький",
        "littletext1": "Привет, меня зовут Маленький и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        "littletext2": "Привет, меня зовут Маленький и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        // alisa
        "alisatitle": "Рус Алиса",
        "alisatext1": "Привет, меня зовут Алиса и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        "alisatext2": "Привет, меня зовут Алиса и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
    },
    "english": {
        // petro
        "petrotitle": "English Petro",
        "petrotext1": "Hi, i'm cool Petro and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        "petrotext2": "Hi, i'm cool Petro and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        // little
        "littletitle": "English Little",
        "littletext1": "Hi, i'm cool Little and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        "littletext2": "Hi, i'm cool Little and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        // alisa
        "alisatitle": "English Alisa",
        "alisatext1": "Hi, i'm cool Alisa and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        "alisatext2": "Hi, i'm cool Alisa and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
    }
}