var data = {
    "uzbek": {
        // petro
        "petrotitle": "O'zbek Petro",
        "petrotext1": "Salom men Petro va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        "petrotext2": "Salom men Petro va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        // little
        "littletitle": "O'zbek Mayda",
        "littletext1": "Salom men Mayda va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        "littletext2": "Salom men Mayda va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        // alisa
        // little
        "alisatitle": "O'zbek Alisa",
        "alisatext1": "Salom men Alisa va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        "alisatext2": "Salom men Alisa va unga yarash ish qilishinga to'gri kelib qoldi. Dizayn va kompozitsiyani baholashda o'qilishi mumkin bo'lgan matn diqqatni jamlashni qiyinlashtirishi, shablonni ko'proq yoki kamroq standart to'ldirishni ta'minlashi, shuningdek, xatboshilardagi harflar va bo'shliqlarning haqiqiy taqsimlanishini ta'minlashi allaqachon ma'lum bo'lgan. oddiy takrorlash bilan. Ko'pgina tartib dasturlari va HTML muharrirlari standart matn sifatida Lorem Ipsum dan foydalanadilar.",
        // ORIGAMIB - uzb
        "origamibtitle": "Oy jodugar va origami bola",
        "origamibtext1": "Olisda, eng chuqur o'rmonda kichkina kottej bor edi. Monika ismli oy jodugar yashardi.",
        "origamibtext2": "Nega uni Oy jodugar deb atashganini bilasizmi? Buning sababi, u o'z biznesini faqat to'lin oy bo'lgan kechalarda ochadi. Uni taniganlar uni shu nom bilan chaqirishardi.",
        "origamibtext3": "Oy jodugarining do'koni qiziqarli qadimiy toshlar, hayvonlarning tana go'shti va har xil iksirlar bilan to'la. Biroq, oy jodugaridagi eng noyob narsa uning origamisidir. U buklagan har bir varaq uning sehri tufayli jonlandi. Oy jodugar bo'sh vaqtlarida gullar, qayiqlar va hasharotlarni to'plashni yaxshi ko'radi. Tez orada butun uy origami san'ati bilan to'ldirildi.",
        "origamibtext4": "“Yo xudoyim, mening kichkina uyimda boshqa joy qolmadi. Buni tushunish uchun menga yordam kerak! ” — deb o‘yladi oy jodugar. U kichik yordamchilar yasash uchun qog'ozni yig'ishni boshladi.",
        "origamibtext5": "Biroq, yirtqich oy jodugar biroz beparvo bo'lishi mumkin. U tasodifan ulardan birini shisha idishga to‘g‘ri yopilmagan sehrli iksiri yoniga tashladi.",
        "origamibtext6": "Sehrli aura sehrli qog'ozlarni sezdi va buklangan qog'oz bola tomon yurdi. Biroz vaqt o'tgach, kichkina qog'oz bola o'rnidan o'tirdi. U atrofga qiziqib qaradi.",
        "origamibtext7": "“Bu yerda hech kim yo‘q. Ko'rinib turibdiki, men biroz zavqlanaman! — kuldi gazetachi. U tezda stolga yugurdi va pishiriqlarni ko'rdi. U tishlab oldi, yana bir tishlab oldi va stol ustiga maydalangan parchalar sochildi. Yaqinlashib kelayotgan shovqinni eshitib, shosha-pisha o‘rnidan turdi-da, tebranuvchi kursidan sirg‘alib, yerga tushdi. U hayajonda “Men dunyoni kashf qilaman!” deb baqirdi.",
        "origamibtext8": "U yashirincha eshikdan o'tib, o'z sarguzashtiga yo'l oladi.",
        "origamibtext9": "Yo‘lida davom etarkan, bir qishloqqa duch keldi. Bu vaqtga kelib u allaqachon och edi. Qog'ozboz yaqin atrofdagi qandolatxonani ko'rib, do'konga qarashga qaror qildi. Assortimentda lolipop, lolipop va shokolad bor edi. U birin-ketin yutdi-yu, do‘kondor uni ko‘rganini payqamadi.",
        "origamibtext10": "'O'g'ri!' Do‘kondor qichqirdi va qog‘ozbozning orqasidan quvib ketdi. 'Oh oh'. Qog‘ozboz qo‘lga tushganini bilgach, deraza oldiga borib, g‘oyib bo‘ldi. Aynan shu payt shunday kuchli shamol esdiki, u esadi va u shamol bilan uchib bu joyni tark etishga muvaffaq bo'ldi. “Uf, bu yaqin edi! Men shunday sarguzashtchiman! U bu haqda ustunlik hissi bilan o'yladi.",
        // TIGBUG - uz
        "tigbugtitle": "Kichik dars",
        "tigbugtext1": "Tayga ismli yaramas yo'lbars boshqa hayvonlarni masxara qildi, chunki u boshqalardan ko'ra ko'proq masxara va shafqatsiz ko'rinardi. Qachonki u boshqa kichikroq hayvonlarni ko'rsa, u ularning ustidan kuladi yoki ularni itarib yuboradi. Hamma undan qo‘rqib, undan qochdi.",
        "tigbugtext2": "Tayga o'rmonda yolg'iz qolganda, u zerikib ketdi. Maqsadsiz yurganidan so‘ng u yaqin atrofdagi daraxt tagida mudrab ketdi. Uyquchan holatda bo'lgan Taiga birdan qichishishni his qildi. Avvaliga u bir oz tirnadi. Biroq, qichishish kuchayib, qichishishni boshladi. Tayga to'satdan kuchli qichishishga dosh bera olmadi, bu uning o'tirishiga va o'zini ko'p tirnalishiga olib keldi.",
        "tigbugtext3": "“Mening tanamda aynan nima bor? Meni o'z holimga qo'yinglar!' Tayga baqirdi. Kichkina bir hasharot yo'lbarsning mo'ylovi oldiga kelib, unga qo'l silkitib: 'Salom, mening ismim Buggy', dedi. Tayga mo'ylovini qimirlatib, Buggini yuzidan itarib yubormoqchi bo'ldi. Biroq, Buggi chetlab o'tib, boshining tepasiga sakrab tushdi. “Siz kichkina narsasiz. Mendan uzoqroq turing! O‘zing kichkina jonzot ekansan, menga qarshi chiqishga qanday jur’at qilasan? Men seni kaltaklayman! - qichqirdi Taiga.",
        "tigbugtext4": "Tayga boshini pastga tushirdi va Buggyni panjalari bilan boshidan silkitdi. Buggy tezda orqasiga sakrab tushdi. Tayga yana panjalari bilan orqasiga o'tishga urindi, lekin Buggyni ushlay olmadi. Bu Tyga nihoyat bug'i tugamaguncha bir muddat davom etdi.",
        "tigbugtext5": "Meni yolg'iz qoldirishdan oldin nima istaysiz? — hafsalasi pir bo'lib so'radi Tayga. “Hozir bu mening hududim”, deb g'o'ldiradi qo'ng'iz yashiringan joyidan chiqib.",
        "tigbugtext6": "“Sizning hududingiz” deganda aynan nimani nazarda tutyapsiz? Siz mening tanamdasiz ». - dedi Taiga. “Men shu yerda qolaman. Siz meni haydab ketolmaysiz”. - javob berdi Buggy.",
        "tigbugtext7": "Bu Taygani g'azablantirdi va uni Buggydan qutulishga qaror qildi.",
        "tigbugtext8": "Taiga qo'ng'izni silkitish uchun tanasini kuchli silkita boshladi. U juda yumshoq boshlandi va tartibsiz silkinishga o'tdi. Biroz vaqt o'tgach, Tyga barcha silkinishdan boshi aylanib ketdi. U Buggyni yo'q qilganiga ishonib, to'xtadi. Ajablanarlisi shundaki, u yana o'sha siqilishni his qildi. — Men hali ham shu yerdaman, — hazillashdi Buggi.",
        "tigbugtext9": "Keyin Taiga butun tanasi bo'ylab Buggyni mushtlay boshladi. Badaniga qamchi urgan sari chidab bo'lmas his qildi. “Of! Butun vujudim chidab bo'lmas og'riqni boshdan kechirmoqda ». U qichqirdi. Nopok Buggy uning quloqlariga yaqinlashdi va unga kula boshladi.",
        "tigbugtext10": "Keyin g'azablangan Tayga erga yotdi va Buggy ustidan o'tishga harakat qila boshladi. Biroq, u minib ketayotib, yaqin atrofdagi o'tkir novdani payqamadi, bu esa uni qattiq sanchdi. U azobdan qichqirdi.",
        "tigbugtext11": "Bu safar Buggy uning quloqlarini tishlay boshladi. Tayga yanada balandroq qichqirdi. 'Iltimos, to'xtating.'Qattiq dard chekayotgani uchun yolvordi. 'Bundan buyon siz boshqa hayvonlarni qo'rqitish va masxara qilishni bas qilishingiz kerak', dedi qo'ng'iz. 'Agar bo'lmasa, men qaytib, mo'ynalaring ostida abadiy yashirinaman. Meni eshitayapsizmi? - dedi Buggy.",
        "tigbugtext12": "“Albatta qilaman. Men boshqa hayvonlarga ozor bermayman”. - javob berdi Taiga. Bu so'zlar bilan Buggy uchib ketdi.",
        "tigbugtext13": "O'sha kundan boshlab Taiga Buggyning so'zlarini esladi va boshqa hayvonlarni bezovta qilmadi.",
        "tigbugtext14": "Oxiri.",
    },
    "russian": {
        // petro
        "petrotitle": "Рус Петро",
        "petrotext1": "Привет, меня зовут Петро и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        "petrotext2": "Привет, меня зовут Петро и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        // little
        "littletitle": "Рус Маленький",
        "littletext1": "Привет, меня зовут Маленький и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        "littletext2": "Привет, меня зовут Маленький и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        // alisa
        "alisatitle": "Рус Алиса",
        "alisatext1": "Привет, меня зовут Алиса и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        "alisatext2": "Привет, меня зовут Алиса и я капуэро! Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации. Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию.",
        // ORIGAMIB - rus
        "origamibtitle": "Лунная ведьма и мальчик-оригами",
        "origamibtext1": "Далеко-далеко, в глухом лесу стоял небольшой домик. Жила-была лунная ведьма по имени Моника.",
        "origamibtext2": "Знаете, почему ее называют Лунной ведьмой? Это потому, что она открывает свой бизнес только в полнолуние. Люди, которые знали ее, называли ее этим именем.",
        "origamibtext3": "В магазине Лунной ведьмы полно интересных древних камней, туш животных и всевозможных зелий. Однако самое уникальное в лунной ведьме — это ее оригами. Каждый лист бумаги, который она сложила, ожил благодаря ее волшебству. Лунная ведьма очень любит складывать цветы, лодки и насекомых в свободное время. Вскоре весь дом был заполнен произведениями искусства оригами.",
        "origamibtext4": "«О боже, в моем крошечном домике больше нет места. Мне нужна помощь, чтобы разобраться!» — в смятении подумала лунная ведьма. Она начала складывать бумагу, чтобы получились маленькие помощники.",
        "origamibtext5": "Однако неряшливая лунная ведьма может быть немного небрежной. Она случайно уронила одну из них рядом со своим волшебным зельем, которое не было должным образом запечатано в стеклянной банке.",
        "origamibtext6": "Магическая аура почувствовала волшебные бумаги и направилась к сложенному бумажному мальчику. Через некоторое время крошечный бумажный мальчик сел. Он с любопытством огляделся вокруг.",
        "origamibtext7": "«Здесь никого нет. Похоже, я собираюсь повеселиться!» газетчик усмехнулся. Он быстро подбежал к столу и увидел печенье. Он откусил, еще раз откусил, и крошки рассыпались по всему столу. Услышав приближающийся шум, он поспешно встал, соскользнул с кресла-качалки и приземлился на землю. Он в экстазе закричал: «Я иду исследовать мир!»",
        "origamibtext8": "Он украдкой проскальзывает в дверной проем и отправляется в свое приключение.",
        "origamibtext9": "Продолжая свой путь, он наткнулся на деревню. К этому моменту он уже был голоден. Разносчик газет увидел неподалеку кондитерский домик и решил заглянуть в магазин. В ассортименте были леденцы, леденцы и шоколад. Он глотал одно за другим и не замечал, что лавочник его видел.",
        "origamibtext10": " 'Вор!' Лавочник закричал и погнался за разносчиком газет. «Ой-ой». Как только разносчик газет понял, что его поймали, он подошел к окну и скрылся. В этот самый момент был порыв ветра такой силы, что он дул, и он смог покинуть это место, летя по ветру. «Фу, это было близко! Я такой авантюрист! Он размышлял об этом с чувством превосходства.",
        // TIGBUG - rus
        "tigbugtitle": "Крошечный урок",
        "tigbugtext1": "Озорной тигр по имени Тайга издевался над другими животными, так как казался массивнее и свирепее других. Всякий раз, когда он видит других более мелких животных, он либо смеется над ними, либо толкает их. Все избегали его, потому что боялись его.",
        "tigbugtext2": "Однажды Тайга был один в лесу, ему было скучно. После бесцельной прогулки он задремал и задремал под ближайшим деревом. Находясь в сонном состоянии, Тайга внезапно почувствовал зуд. Сначала он просто слегка почесался. Однако зуд усилился, и он начал чесаться. Тайга не мог вынести внезапного сильного зуда, из-за которого он сел и сильно почесался.",
        "tigbugtext3": "«Что именно у меня на теле? Отстань от меня!' — взревел Тайга. Маленький жучок подкрался к усам тигра, помахал ему и сказал: «Привет, меня зовут Багги». Тайга дернул усами, пытаясь сбросить Багги со своего лица. Однако Багги увернулся и спрыгнул ему на макушку. «Ты крошечная штучка. Держись подальше от меня! Как ты посмел бросить мне вызов, когда ты всего лишь маленькое существо? Я тебя шлепну! — кричал Тайга.",
        "tigbugtext4": "Тайга опустил голову и безуспешно смахнул лапами Багги с головы. Багги быстро запрыгнул ему на спину. Тайга снова попытался использовать свои когти, чтобы добраться до его спины, но не смог поймать Багги. Это продолжалось некоторое время, пока, в конце концов, Tyga не выдохлась.",
        "tigbugtext5": "— Чего ты хочешь, прежде чем оставишь меня в покое? — разочарованно спросил Тайга. «Теперь это моя территория», — пробормотал жук, выходя из своего укрытия.",
        "tigbugtext6": "«Что именно вы подразумеваете под «вашей территорией»? Ты на Моем теле». — сказал Тайга. «Я останусь здесь. Ты не можешь меня прогнать». — ответил Багги.",
        "tigbugtext7": "Это взбесило Тайгу и заставило его решить избавиться от Багги.",
        "tigbugtext8": "Тайга начал энергично трясти свое тело, чтобы стряхнуть жука. Он начал очень мягко и перешел к более беспорядочной тряске. Через некоторое время у Tyga закружилась голова от всех раскачиваний. Он остановился, полагая, что уничтожил Багги. К своему удивлению, он снова почувствовал это покалывание. — Я все еще здесь, — пошутил Багги.",
        "tigbugtext9": "Затем Тайга начал бить Багги руками и хвостом по всему телу. Чем больше он хлестал свое тело, тем невыносимее он себя чувствовал. «Ой! Все мое тело испытывает мучительную боль». Он закричал. Нахальный Багги приблизился к его ушам и начал посмеиваться над ним.",
        "tigbugtext10": "Затем разъяренный Тайга лёг на землю и начал кататься, пытаясь перебраться через Багги. Однако, пока он катался, он не заметил рядом острую ветку, которая сильно его уколола. Он закричал в агонии.",
        "tigbugtext11": "На этот раз Багги начал кусать его за уши. Тайга завыл еще громче. 'Пожалуйста остановись.' Он умолял, так как ему было так больно. «С этого момента вы должны перестать пугать и издеваться над другими животными», — сказал жук. «Если нет, я вернусь и навсегда спрячусь под твоими мехами. Ты слышишь меня?' — сказал Багги.",
        "tigbugtext12": "«Конечно, буду. Я не собираюсь снова причинять боль другим животным». Тайга ответил. С этими словами Багги улетел.",
        "tigbugtext13": "С того дня Тайга вспомнил слова Багги и больше не беспокоил других животных.",
        "tigbugtext14": "Конец.",
    },
    "english": {
        // petro
        "petrotitle": "English Petro",
        "petrotext1": "Hi, i'm cool Petro and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        "petrotext2": "Hi, i'm cool Petro and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        // little
        "littletitle": "English Little",
        "littletext1": "Hi, i'm cool Little and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        "littletext2": "Hi, i'm cool Little and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        // alisa
        "alisatitle": "English Alisa",
        "alisatext1": "Hi, i'm cool Alisa and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        "alisatext2": "Hi, i'm cool Alisa and i'm to a capuero! It has long been found out that when evaluating design and composition, readable text makes it difficult to concentrate, that it provides more or less standard filling in the template, as well as the real distribution of letters and spaces in paragraphs, which is not obtained with simple duplication. Many layout programs and HTML editors use Lorem Ipsum as their default text.",
        // ORIGAMIB - eng
        "origamibtitle": "The moon witch and the origami boy",
        "origamibtext1": "Far far away, in the deepest forest was a small cottage. There lived a moon witch named, Monica.",
        "origamibtext2": "Do you know why she’s called a Moon Witch? That’s because she only opens her business on nights when there is a full moon. The people who know her called her by that name.",
        "origamibtext3": "The Moon Witch’s shop is packed with many interesting ancient stones, animal carcasses, and potions of all sorts. However, the most unique thing about the moon witch is her origami. Every piece of paper she folded, come alive with her magic. The moon witch absolutely love folding flowers, boats and insects during her leisure time. Soon, the whole house was filled with origami art.",
        "origamibtext4": "“Oh dear, there are no more space in my tiny house. I need some help to clear up!” The moon witch thought in dismay. She began folding some paper to make into little helpers.",
        "origamibtext5": "However, the messy moon witch can be a little careless. She accidentally dropped one of them near her magic potion which was not sealed properly in the glass jar.",
        "origamibtext6": "The magic aura senses the magical papers and drifted towards the folded paper boy. After a while, the tiny paper boy sat up. It looked around to check out the surroundings curiously.",
        "origamibtext7": "“There’s no one here. Looks like I’m going to have some fun!” the paper boy grinned. Quickly, he ran to the table and saw some cookies. He took a bite, and another bite, causing the crumps to fall all over the table. When he heard some noise coming, he hastily got up, slid down the rocking chair and landed on the ground. He yelled out in ecstasy, “I am going out to explore the world!”",
        "origamibtext8": "Stealthily, he slides himself through the gap of the door and out on his adventure.",
        "origamibtext9": "As he continued his journey, he came across a village. At this point, he was already famished. The paper boy saw a candy house nearby and decided to pop into the shop. There were a wide variety of candies, lollipops and chocolates. He gobbled one after another and did not notice that the shopkeeper saw him.",
        "origamibtext10": "“Thief!” The shopkeeper shouted and chased after the paper boy. “Uh-oh.” Once the paper boy realized he was caught, he proceeded to the window and took off. At that very moment, there was a gust of wind so powerful that it blew, and he was able to flee the area by flying with the wind.  “Phew, that was close! I am such an adventurer! He reflected on it with a sense of superiority.",
        // TUGBUG - eng
        "tigbugtitle": "Tiny lesson",
        "tigbugtext1": "A mischievous tiger named Tyga bullied other animals as he appeared massive and more ferocious than others. Whenever he sees other smaller animals, he either makes fun of them or pushes them. Everyone avoided him because they were terrified of him.",
        "tigbugtext2": "One day, Tyga was alone in the woods, feeling bored. After walking around aimlessly, he got drowsy and napped under a nearby tree. While in his sleepy state, Tyga suddenly felt an itchy sensation. At first, he merely scratched lightly. However, the itch became more intense, and he began scratching. Tyga could not bear the sudden severe itch that he sat up and scratched hard.",
        "tigbugtext3": "“What exactly is it on my body? Get off of me!” Tyga roared. A little bug crept up to the tiger’s whiskers, waved at him, and said, “Hello, my name is Buggy.” Tyga twitched his whiskers in an attempt to expel Buggy from his face. However, Buggy dodged it and jumped off to the top of his head. “You tiny little thing. Stay away from me! How dare you challenge me when you are just a small little creature? I’m going to smack you flat!” Tyga yelled.",
        "tigbugtext4": "Tyga lowered his head and used his paws to brush Buggy off his head unsuccessfully. Buggy quickly hopped to his back. Tyga tried again to use his claws to reach his back but could not get Buggy. This went on for some time until, eventually, Tyga was exhausted.",
        "tigbugtext5": "“What do you want before you leave me alone?” Tyga asked in frustration. “This is my territory now,” the bug murmured as he emerged from his hiding place.",
        "tigbugtext6": "“What exactly do you mean by “your territory”? You are on MY body.” Tyga said. “I’ll be staying here. You can’t drive me away.” Buggy replied.",
        "tigbugtext7": "This infuriated Tyga and made him determined to get rid of Buggy.",
        "tigbugtext8": "Tyga started shaking his body vigorously to shake off the bug. He began very gently and progressed to a more erratic shaking. After a while, Tyga became dizzy from all the swinging. He came to a halt, believing he had exterminated Buggy. To his surprise, he felt that tingly sensation again. “I’m still here,” Buggy joked.",
        "tigbugtext9": "Tyga then began striking Buggy with his hands and tail all around his body. The more he whipped his body, the more unbearable he felt. “Ouch! My entire body is in excruciating pain.” He yelled. The cheeky Buggy got close to his ears and started chuckling at him.",
        "tigbugtext10": "The enraged Tyga then lay down on the ground and began rolling around, attempting to move over Buggy. However, as he rolled around, he did not notice a sharp branch nearby, which poked him hard. He screamed in agony.",
        "tigbugtext11": "This time, Buggy proceeded to bite him in the ears. Tyga wailed louder. “Please stop.” He pleaded as he was in so much pain. “From now on, you must stop scaring and bullying the other animals,” the bug said. “If not, I’ll return and hide under your furs forever. Do you hear me?” Buggy said.",
        "tigbugtext12": "“I will, of course. I’m not going to hurt the other animals again.” Tyga responded. With that, Buggy flew away.",
        "tigbugtext13": "Since that day, Tyga remembered Buggy’s words and did not disturb the other animals again.",
        "tigbugtext14": "The end.",
        // MNK
        "mnktitle":"Monty's Rashes",
        "mnktext1": "“Mum, I don’t feel well.” Monty, the monkey, said as he lay on his bed. “I am having a headache and feel weak in general.” He complained.",
        "mnktext2": "“Oh dear, let me check with a thermometer to see if you are running a fever.” Mother replied. After the mother monkey took Monty’s temperature, she realised that he is indeed having one.",
        "mnktext3": "“Monty, you are running a fever. Next up, let’s do a Covid-19 test with the test kit to see if you are down with the virus.” Mother continued. After taking his swaps, the results turned out to be negative. “Phew.” Mother heaved a sigh of relief.",
        "mnktext4": "“I will prepare some fever medicine for you, Monty. Rest at home for today.” Mother said as she went to get medicine for Monty. After taking them, Monty continued resting for the day.",
        "mnktext5": "The following day, Monty woke up to go to the washroom when he gave a loud squeal suddenly. Mother monkey rushed into Monty’s room to check what had happened. When she entered the room, she was shocked. Monty’s face started developing bumps!",
        "mnktext6": "“Mum, these bumps are so itchy!” Monty wailed as he scratched all over his face. “Don’t touch your face, Monty! Let me bring you to the doctor now!” Mother said anxiously.",
        "mnktext7": "Quickly, Monty and his mother rushed to the clinic. After some time, it was finally Monty’s turn to see the doctor. The doctor looked at the bumps and asked a few questions, “Did you have a headache and a fever?”",
        "mnktext8": "Monty replied, “Yes.”",
        "mnktext9": "“Did you feel some muscle aches and feeling of tiredness?” the doctor continued.",
        "mnktext10": "Monty said, “Yes.”",
        "mnktext11": "Next, the doctor examines the bumps on his face and body.",
        "mnktext12": "“I think you might have monkeypox.” The doctor said as he took samples of the fluid from the bumps.",
        "mnktext13": "Mother monkey was shocked. “What is that? Is there any cure?”",
        "mnktext14": "“Well, Monkeypox is caused by a virus. It has been around since the 1950s. It occurs primarily in tropical rainforest areas of central and west Africa and is occasionally exported to other regions. Although it resembles smallpox, it is much less contagious. Unfortunately, as of now, there are still no cures, but vaccines are being developed.” The doctor explained.",
        "mnktext15": "“But doctor, how do they spread? I don’t want my family to get it.” Monty asked sadly.",
        "mnktext16": "“It can spread through close contact, air droplets from breath, body fluids from the infected person or even contaminated materials such as beddings from the infected.”",
        "mnktext17": "“Mum, please stay away from me. I do not wish to infect you.” Monty sulked.",
        "mnktext18": "“Yes, it will be great if your mother can wash her hands frequently, especially when she is in contact with you, and also wear a mask!” the doctor advised.",
        "mnktext19": "“Please do so, mum. I don’t want you to have ugly face with rashes like me.” Monty looked at his mum sadly.",
        "mnktext20": "His mother let out a tiny smile, not knowing if she should laugh or cry.",
        "mnktext21": "The end.",
    }
}


// TUGBUG
// "tigbugtitle": "",
// "tugbugtext1": "",
// "tugbugtext2": "",
// "tugbugtext3": "",
// "tugbugtext4": "",
// "tugbugtext5": "",
// "tugbugtext6": "",
// "tugbugtext7": "",
// "tugbugtext8": "",
// "tugbugtext9": "",
// "tugbugtext10": "",
// "tugbugtext11": "",
// "tugbugtext12": "",
// "tugbugtext13": "",
// "tugbugtext14": "",

// "origamibtext1": "",
        // "origamibtext2": "",
        // "origamibtext3": "",
        // "origamibtext4": "",
        // "origamibtext5": "",
        // "origamibtext6": "",
        // "origamibtext7": "",
        // "origamibtext8": "",
        // "origamibtext9": "",
        // "origamibtext10": "",
        // "origamibtext11": "",
        // "origamibtext12": "",












// STOCK
// ORIGAMIB - rus
// "origamibtitle": "",
// "origamibtext1": "",
// "origamibtext2": "",
// "origamibtext3": "",
// "origamibtext4": "",
// "origamibtext5": "",
// "origamibtext6": "",
// "origamibtext7": "",
// "origamibtext8": "",
// "origamibtext9": "",
// "origamibtext10": "",
// "origamibtext11": "",
// "origamibtext12": "",
// "origamibtext13": "",
// "origamibtext14": "",
// "origamibtext15": "",
// "origamibtext16": "",
// "origamibtext17": "",
// "origamibtext18": "",
// "origamibtext19": "",
// "origamibtext20": "",